apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: solr
spec:
  releaseName: solr-operator
  interval: 5m
  timeout: 5m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: solr-operator
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: apache-solr-charts
        namespace: flux-system
