apiVersion: v1
kind: Service
metadata:
  name: solr-admin-lb
  namespace: solr1
spec:
  type: LoadBalancer  #####
  selector:
    solr-cloud: my-solrcloud-v3
    technology: solr-cloud
  ports:
    - name: solr
      port: 8983
      targetPort: 8983

