apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: my-solrcloud-v9
  namespace: solr3
spec:
  replicas: 2
  solrImage:
    repository: solr
    tag: 9.5.0

  # Persistent data storage using PVCs
  dataStorage:
    persistent:
      reclaimPolicy: Retain
      pvcTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
          storageClassName: default

  # --- CORRECTED SECTION ---
  # Use podTemplate for general pod configuration, including affinity and volume mounts
  podTemplate:
    metadata:
      labels: # Labels for the SolrCloud pods
        solr-cloud: my-solrcloud-v9
        technology: solr-cloud
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: solr-cloud
                    operator: In
                    values:
                      - my-solrcloud-v9
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: solr # This name is usually fixed for the main Solr container
          volumeMounts:
            - name: data # The 'data' volume is typically provided by the Solr operator via dataStorage
              mountPath: /var/solr
          # You might also want to add resource limits/requests here for the solr container
          # resources:
          #   requests:
          #     cpu: "500m"
          #     memory: "1Gi"
          #   limits:
          #     cpu: "1"
          #     memory: "2Gi"
  # --- END CORRECTED SECTION ---

  zookeeperRef:
    provided:
      replicas: 3
      persistence:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
