apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: my-solrcloud-v9
  namespace: solr3
spec:
  replicas: 2
  solrImage:
    repository: solr
    tag: 9.5.0

  # Persistent data storage using PVCs
  dataStorage:
    persistent:
      reclaimPolicy: Retain
      pvcTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
          storageClassName: default

  # Pod anti-affinity to spread across nodes
  solrPodOptions:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: solr-cloud
                  operator: In
                  values:
                    - my-solrcloud-v9
            topologyKey: "kubernetes.io/hostname"

    # Solr data is written here (will be backed by the PVC named 'data')
    volumeMounts:
      - name: data
        mountPath: /var/solr

  customSolrKubeOptions:
    podOptions:
      labels:
        solr-cloud: my-solrcloud-v9
        technology: solr-cloud

  zookeeperRef:
    provided:
      replicas: 3
      persistence:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

