apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: my-solrcloud-v9
  namespace: solr3
spec:
  replicas: 2
  solrImage:
    repository: solr
    tag: 9.5.0

  # Use persistent PVC-based storage for Solr data
  dataStorage:
    persistent:
      reclaimPolicy: Retain
      pvcTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: default  # Adjust if you're using a different class

  # Optional labels and volume mount
  customSolrKubeOptions:
    podOptions:
      volumeMounts:
        - name: data
          mountPath: /var/solr
      labels:
        solr-cloud: my-solrcloud-v9
        technology: solr-cloud

  zookeeperRef:
    provided:
      replicas: 3
      persistence:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

